# Generated by Django 3.2 on 2021-04-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("miner", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asctime", models.DateTimeField(auto_now_add=True)),
                ("level_name", models.CharField(max_length=50)),
                ("message", models.TextField()),
                ("main_news", models.BooleanField(default=False)),
                ("importance", models.FloatField(default=0)),
            ],
        )
    ]
