# Generated by Django 3.2 on 2021-04-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("miner", "0002_log")]

    operations = [
        migrations.RemoveField(model_name="log", name="importance"),
        migrations.RemoveField(model_name="log", name="main_news"),
        migrations.AddField(
            model_name="news",
            name="importance",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="news",
            name="main_news",
            field=models.BooleanField(default=False),
        ),
    ]
