# Generated by Django 3.2 on 2021-04-25 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("miner", "0003_auto_20210425_0708")]

    operations = [
        migrations.AlterModelOptions(
            name="log",
            options={"verbose_name": "Лог", "verbose_name_plural": "Логи"},
        ),
        migrations.AlterModelOptions(
            name="news",
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
    ]
