# Generated by Django 3.2 on 2021-04-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("miner", "0004_auto_20210425_0817")]

    operations = [
        migrations.AlterField(
            model_name="news", name="time", field=models.DateTimeField()
        )
    ]
