# Generated by Django 3.2 on 2021-04-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("miner", "0005_alter_news_time")]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["-main_news", "-importance"],
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        )
    ]
