# Generated by Django 3.2 on 2021-04-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("miner", "0006_alter_news_options")]

    operations = [
        migrations.AlterField(
            model_name="log", name="asctime", field=models.DateTimeField()
        )
    ]
