# Generated by Django 3.2 on 2021-04-26 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("miner", "0008_remove_log_asctime")]

    operations = [
        migrations.AddField(
            model_name="log",
            name="time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        )
    ]
