# Generated by Django 3.2 on 2021-04-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("miner", "0010_alter_log_time")]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="time",
            field=models.DateTimeField(auto_now=True),
        )
    ]
